### PR TITLE
Docs: Note about getting a reference to the device abstraction layer

### PR DESCRIPTION
**Pull request by owensgit**
One of the problems I had when understanding how to implement networking with TAL was that I didn't know how to obtain a reference to the device abstraction later. 

I've added a note in the networking and storage pages which I think would be really useful for new adopters.

Please let me know what you think.

### CODE REVIEW

**Comment by dhurrell** [comment]
Thanks again for your contribution, Owen!

Sorry to be a pain though, but ideally we don't want embedded HTML in our Markdown source files (apart from the bare minimum). Is it possible to use pure Markdown instead?

As a suggestion for an alternative approach, it might make sense to add your note to the FAQ as a question and answer:
http://fmtvp.github.io/tal/faq.html
https://raw.githubusercontent.com/fmtvp/tal/gh-pages/faq.md

That way we can simply link to the FAQ page any time we mention obtaining a reference to the device, rather than duplicating the same information everywhere.

Thanks,
David

**Comment by owensgit** [comment]
Thanks David,

That's a good idea, I'll add it to the FAQ's :)

**Comment by owensgit** [comment]
@dhurrell - I've update the as suggested. I'd be happy to change the wording, positioning, etc if needed. Just let me know.

**Comment by dhurrell** [comment]
Looks great - thanks Owen!

**Pull request merged**
