### PR TITLE
Require def migration

### LINKED ISSUE #345: require.def() does not work with recent versions of requireJS
The TAL code uses require.def() in place of define().  Incorporating TAL into code which already uses requireJS exposes the problem above: requireJS no longer has require.def().  Even if the TAL's requireJS is deployed, the problem still impacts the build tools, e.g. jasmine's requirejs "template", and the requireJS optimiser/minifier.  There are ways round each issue, to be sure, but each one is a new kludge in the build.  Is there any reason require.def has been chosen in preference to define?  Would there be any impact if define is used instead?

### PR DESCRIPTION
**Pull request by AlexChesters**
This would resolve #345 and changes all occurrences of `require.def` inside [`static/script`](https://github.com/fmtvp/tal/tree/master/static/script) to use `define`.

Obviously this well need a thorough review as it touches everything

### CODE REVIEW

**Comment by AlexChesters** [comment]
I've no idea how the change in #343 made it in here, so I've reverted it in this PR.

**Comment by AlexChesters** [comment]
@lukejpreston no it wasn't but it somehow found its way in, reverted it so it should have no effect

**Comment by lukejpreston** [comment]
It might be an idea to get a handful of devices and check this version of TAL before this gets merged but pending passing tests I see no reason not to

**Comment by AlexChesters** [comment]
Closing this as it's a bit of a mess with that accidental commit, will open a new one with the intended changes.

**Pull request closed without merging**
