### PR TITLE
Fix get methods in live facade

### PR DESCRIPTION
**Pull request by tsadlerBBC**

### CODE REVIEW

**Comment by dhurrell** [comment]
When setting up the expected values, would it be better to use Sinon to stub out each function on the underlying media player and return the expected value using .returns()? Otherwise the tests are very white-box and they will start to fail if any of the internals of the underlying media player change (e.g. _mimeType, or how getCurrentTime() works).

Sorry this even happened by the way! Daft thing not to spot in review.

**Comment by tsadlerBBC** [comment]
Thanks David,

Good point. We will still need to rely on the mediaplayer API remaining the same, but as it's public, that makes sense. We will also be testing a smaller unit this way - currently they are slightly integration-y as well as being white box.

**Comment by tsadlerBBC** [comment]
Changes made - hopefully OK to merge now!

**Comment by dhurrell** [comment]
You could get the underlying media player with `device.getMediaPlayer()` to avoid another private member access, but in the interests of not spending all day nitpicking I'll merge it in. ;)

**Pull request merged**
