### PR TITLE
Css prefixes fix

### PR DESCRIPTION
**Pull request by povilas0**
This fix is for IPTV-352. This fixes the issue with css3 animation on FVP devices. The fix was done by changing how css prefixes where added to element's style attribute. Before TAL was sniffing device browser's user agent to find out which prefixes need to be added. Now TAL does not sniff UA, but adds all possible prefixes to css properties and device's browser decides which property needs to be used.

### CODE REVIEW

**Comment by sdclibbery** [comment]
This looks great. Much cleaner and simpler, and the nasty UA sniffing code is gone. If the devices are happy with this approach, then it's definitely a win  :-)

**Comment by subsidel** [comment]
:+1:  for removing propertyMap

**Comment by cloud1ess** [comment]
Looks good in general.

We have a convention of using forEach in the unit tests, there are a couple of for loops in there that could be done this way.

**Comment by povilas0** [comment]
Old style 'for' loops have been replaced with 'forEach' in this commit: 9c6540f5f049aeb62bb06c5d3c24a7eb92b47890

**Comment by tsadler1988** [comment]
Just remember not to use forEach in production code as it is an ES5 feature :).

**Pull request merged**
